### ISSUE TITLE
Requires a buffer as input

### ISSUE THREAD

**Issue by scottinet** [lovell/highwayhash#1]
Hi,

I don't know if the documentation is wrong or if it states a functionality that is not yet implemented, but in its current state, this module takes only a Buffer object as input arguments, while the documentation uses a plain string to show how to use this module.

I would submit a pull request, but I'd rather let you decide if the problem lies in the documentation or the implementation. :-)

To reproduce:

```
$ node -v
v6.9.2
$ node
> const hh = require('highwayhash');
{ asBuffer: [Function: asBuffer],
  asString: [Function: asString],
  asHexString: [Function: asHexString],
  asUInt32Low: [Function: asUInt32Low],
  asUInt32High: [Function: asUInt32High] }

> hh.asHexString(require('crypto').randomBytes(32), Buffer.from('foobar'));
'81aa3aeea2e1f9dd'

> hh.asHexString(require('crypto').randomBytes(32), 'foobar');
Error: Expected input to be a Buffer: foobar
    at assertInput (/var/app/node_modules/highwayhash/index.js:13:11)
    at Object.asHexString (/var/app/node_modules/highwayhash/index.js:30:5)
    at repl:1:4
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:313:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:513:10)
```

**Comment by lovell** [comment]
Hello, you're correct that a Buffer is required as input. The example in the readme is wrong in this case so a PR to fix this would be most welcome.

(I think my original idea was that this module could automagically wrap a string as a Buffer, but on reflection I believe that logic is best left outside this module.)

**Comment by lovell** [comment]
v2.1.0 now available, thank you for the documentation clean-up.
