### ISSUE TITLE
CPU Mining Software Integration?

### ISSUE THREAD

**Issue by samiby** [lovell/highwayhash#10]
Could you please tell me if it is possible to easily integrate the HighWayHash into the most Known CPU Mining Softwares because +80% of the World People are using CPUs!

People are leaving the Crypto Mining World because Electricty costs are very high! So, when implementing a new auto-switchable version with HighWayHash (All OS), we will have the best one! Fast Mining, Fast Jumping to The New Digital World, fast Global Network!

Thanks in advance

**Comment by lovell** [comment]
Sorry, this repo has nothing to do with "crypto" or "mining", and long may it stay that way.
