### ISSUE TITLE
Support for streaming?

### ISSUE THREAD

**Issue by mceachen** [lovell/highwayhash#5]
How do you recommend highwayhash be used for hashing bytestreams?

It seems like the highwayhash library assumes a single buffer interaction--I didn't see anything like a crypto hash `.update(Buffer | string)` method.

**Comment by lovell** [comment]
The underlying API calculates the hash for an entire Buffer at once.

Perhaps generate and store the hash for each fixed-size chunk then hash the concatenated list of hashes at the end?

**Comment by mceachen** [comment]
Sure, that would work.

Given that the underlying library doesn't support streaming, I'll close this now. Thanks for the idea!
