### ISSUE TITLE
N-API support

### ISSUE THREAD

**Issue by NickNaso** [lovell/highwayhash#6]
Hi @lovell ,
I worked on this native addon and I ported it to **[N-API](https://nodejs.org/dist/latest-v8.x/docs/api/n-api.html)**  
You can find my work here: [https://github.com/NickNaso/highwayhash/tree/napi](https://github.com/NickNaso/highwayhash/tree/napi)
If you want experiment with N-API you can create a branch and call it "napi" so I can execute the PR on it. 
After that we can iterate to over it and at the end publish a tagged version of **highwayhash** like reported here: https://nodejs.org/en/docs/guides/publishing-napi-modules/

**Comment by lovell** [comment]
Hi @NickNaso, I'd be happy to accept and merge a PR for this if it's something you're still interested in.

**Comment by NickNaso** [comment]
Hi @lovell it could be great, but before to make a PR I want update and review my work. I will try to do tomorrow.

**Comment by lovell** [comment]
Brilliant, thank you, there's no time pressure.

**Comment by lovell** [comment]
v3.0.0 now available, thanks again for the PR.
