### ISSUE TITLE
Performance Discrepancy

### ISSUE THREAD

**Issue by nickbabcock** [lovell/highwayhash#8]
[I just published a little experiment](https://www.npmjs.com/package/highwayhasher). It's an npm package that binds to the rust port of highwayhash. The rust and C++ implementations have similar performance characteristics, but the npm benchmarks differ by 2x (in favor of the rust bindings). I'm haven't investigated why this occurs (maybe `highwayhash` is not using AVX2 🤷 )

<details>
  <summary>Benchmark Code</summary>
  
  
```js
const { HighwayHash } = require("highwayhasher");
const { asBuffer } = require("highwayhash");
const { assert } = require("console");

const key = Buffer.alloc(32, 1);

function timeIt(name, fn) {
  const start = process.hrtime.bigint();
  const res = fn();
  const end = process.hrtime.bigint();
  console.log(`${name} ${(Number(end - start) * 1e-6).toFixed(2)}ms`);
  return res;
}

(async function () {
  console.time("initialize native");
  const nativeMod = await HighwayHash.loadModule();
  console.timeLog("initialize native");

  const inputs = [
    1,
    10,
    100,
    1000,
    10000,
    100000,
    1000000,
    10000000,
    100000000,
  ];

  // first: a warmup round
  for (let index = 0; index < inputs.length; index++) {
    console.log(`hashing data of size: ${inputs[index]}`);
    const data = Buffer.alloc(inputs[index], 1);
    const native = nativeMod.create(key);
    native.append(data);
    native.finalize64();

    asBuffer(key, data);
  }

  // then record actual timings
  for (let index = 0; index < inputs.length; index++) {
    console.log(`hashing data of size: ${inputs[index]}`);
    const data = Buffer.alloc(inputs[index], 1);

    const nativeRes = timeIt("hash native", () => {
      const native = nativeMod.create(key);
      native.append(data);
      return native.finalize64();
    });

    const thirdRes = timeIt("3rd party", () => {
      return asBuffer(key, data);
    });

    assert(
      Buffer.from(nativeRes.buffer).equals(thirdRes),
      "hash packages agree"
    );
    console.log();
  }
})();
  ```
  
</details>

Figured I'd just drop a line in case there was an unintended performance regression somewhere.

**Comment by lovell** [comment]
Hi Nick, thanks for reporting this, I think I can reproduce this locally:

```
hashing data of size: 10
hash native 0.02ms
3rd party 0.01ms

hashing data of size: 100
hash native 0.01ms
3rd party 0.01ms

hashing data of size: 1000
hash native 0.01ms
3rd party 0.01ms

hashing data of size: 10000
hash native 0.01ms
3rd party 0.01ms

hashing data of size: 100000
hash native 0.02ms
3rd party 0.02ms

hashing data of size: 1000000
hash native 0.10ms
3rd party 0.19ms

hashing data of size: 10000000
hash native 1.18ms
3rd party 2.02ms

hashing data of size: 100000000
hash native 11.90ms
3rd party 21.31ms
```

However when I run with a `highwayhash.node` binary built locally, i.e. not using prebuilt binaries, I see:

```
hashing data of size: 10
hash native 0.02ms
3rd party 0.01ms

hashing data of size: 100
hash native 0.01ms
3rd party 0.01ms

hashing data of size: 1000
hash native 0.01ms
3rd party 0.01ms

hashing data of size: 10000
hash native 0.01ms
3rd party 0.01ms

hashing data of size: 100000
hash native 0.02ms
3rd party 0.02ms

hashing data of size: 1000000
hash native 0.12ms
3rd party 0.11ms

hashing data of size: 10000000
hash native 1.13ms
3rd party 1.11ms

hashing data of size: 100000000
hash native 11.77ms
3rd party 11.29ms
```

I suspect something is going wrong when the CI environment is building release binaries, and as you suggest a lack of AVX2 support could explain the performance difference.

Luckily I'm just switched CI from Travis to GitHub Actions, so I suspect that forcing a new build on the more modern hardware it provides might fix this.

**Comment by nickbabcock** [comment]
Perfect! I cut releases on github and they are AVX2 enabled. Once you cut a new release, I'll update my notes about the performance differences.

**Comment by lovell** [comment]
v3.1.0 is now available with prebuilt binaries generated via GitHub Actions.

Here's what I see using the prebuilt binaries running locally on the same Kaby Lake CPU (with AVX2) as the previous timings:

```
hashing data of size: 1
hash native 0.06ms
3rd party 0.03ms

hashing data of size: 10
hash native 0.03ms
3rd party 0.01ms

hashing data of size: 100
hash native 0.01ms
3rd party 0.01ms

hashing data of size: 1000
hash native 0.01ms
3rd party 0.01ms

hashing data of size: 10000
hash native 0.01ms
3rd party 0.01ms

hashing data of size: 100000
hash native 0.03ms
3rd party 0.02ms

hashing data of size: 1000000
hash native 0.16ms
3rd party 0.11ms

hashing data of size: 10000000
hash native 1.66ms
3rd party 1.07ms

hashing data of size: 100000000
hash native 16.22ms
3rd party 11.17ms
```

I'm unsure why the "hash native" timings are now slower than before, but the "3rd party" timings are now almost the same as the original "hash native" timings.

I added your highwayhasher module to the benchmark tests in https://github.com/lovell/highwayhash/tree/master/bench too, which seems to report it as being slightly slower. My best guess would be something to do with the N-API call overhead given highwayhasher uses 3 per hash compared with highwayhash using 1 per hash.

Thanks again for reporting this - let's leave this open until you've had a chance to confirm this improvement.

**Comment by nickbabcock** [comment]
I can confirm

- `highwayhasher` has seen a performance regression with prebuilt modules (I had cut a release in the meantime) that I must now look into 🤣 
- `highwayhash` is much improved and reaches the expected timings

**Comment by nickbabcock** [comment]
I fixed the performance regression in `highwayhasher` v0.0.4 by cutting releases against 20.04 instead of 18.04 🙄 

Though interestingly, it still appears significantly slower in the benchmark suite here, but that may be due to the 3 NAPI calls instead of 1 as you suspect. You'd think if it had a real world impact it'd show up in the benchmark snippet I posted. Finicky

**Comment by lovell** [comment]
Great, thanks for confirming. The difference in Ubuntu LTS versions will probably be due to optimisation improvements in gcc between 8 and 9.

In terms of benchmark differences, perhaps you could try increasing the entropy of the inputs in your benchmark as it looks like they contain only the value `0x01` so you're likely to be hitting optimised paths that won't occur for "real world" data.
